name: Check PR

on:
  pull_request:
    branches: [ prod ]
    types: [ synchronize ]

env:
  NODE_VERSION: 20.10.0
  ENABLE_CACHE: yes

jobs:
  prepare:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-prepare
      cancel-in-progress: true
    outputs:
      node-version: ${{ steps.variable.outputs.node-version }}
      enable-cache: ${{ steps.variable.outputs.enable-cache }}

    steps:
      - name: Define variables
        id: variable
        run: |
          echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "enable-cache=$ENABLE_CACHE" >> $GITHUB_OUTPUT

  check:
    runs-on: ubuntu-latest
    needs: [prepare]
    concurrency:
      group: ${{ github.ref }}-check-pr
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.prepare.outputs.node-version }}
          cache: ${{ needs.prepare.outputs.enable-cache == 'yes' && 'npm' || '' }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Commit lint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx --no-install commitlint -g commitlint.config.js

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check

      - name: Stylelint check
        run: npm run style:check

      - name: Build check
        run: npm run build -- --throw-warnings
